# Generated by Django 5.0 on 2023-12-30 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0002_remove_user_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='verification_OTP',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
